server {
  absolute_redirect off;
  charset utf-8;
  root /mnt/github-pages;

  error_page 404 /404.html;

  if (-d $request_filename) { rewrite ^(/.*[^/])$ $1/ permanent; }
  rewrite ^(.+)/$ $1;
  try_files $uri $uri/index.html $uri.html =404;
}
